source 'http://rubygems.org'

gem 'rails', '3.0.0'

gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'thin'

gem 'komando', :path => "/Users/francois/Projects/komando"

group :development, :test do
  gem 'interactive_editor'
end

# vim: set ft=ruby
